create API to get user profile details
umiatiyah/my-portfolio-service pull request #2
Opened 2023-10-12 13:07 UTC by umiatiyah

- create method to get list social media by user_profile_id
- create method to get list social media by user_profile_id
- create method to get list social media by user_profile_id
- create method to get list social media by user_profile_id

2023-10-12 15:03 UTC, fathrezza146 requested changes

2023-10-12 15:03 UTC, fathrezza146 commented on response/user_profile.go
> +	UserProfile interface{} `json:"user_profile"`
jgn pake innnterface. trus haruse ada db di dalam property haruse ketambah DB

2023-10-13 13:33 UTC, umiatiyah commented on response/user_profile.go
> +	UserProfile interface{} `json:"user_profile"`
piye? bisa ga pake struct dari model yang udaah ada?

2023-10-15 08:23 UTC, fathrezza146 commented on response/user_profile.go
> +	UserProfile interface{} `json:"user_profile"`
Bisa. Tinggal `json:"smth",db:"smth"`

2023-10-28 16:17 UTC, fathrezza146 approved these changes
LGTM!!!!!!

2023-11-08 17:18 UTC, merged